#IOT-STARTER-KIT nodered demo app for the RPI board

FROM nodered/node-red-docker:rpi

MAINTAINER Rostislav Spinar "rostislav.spinar@iqrf.com"
LABEL maintainer="rostislav.spinar@iqrf.com"

# install the dashboard
RUN npm install node-red/node-red-dashboard

USER node-red

# copy custom flow
COPY ui/flows.json /data/flows.json

# expose port to host
EXPOSE 1880
