##IOT-STARTER-KIT nodered demo app for the UP board

FROM nodered/node-red-docker

MAINTAINER Rostislav Spinar "rostislav.spinar@iqrf.com"
LABEL maintainer="rostislav.spinar@iqrf.com"

# install the dashboard
RUN npm install node-red/node-red-dashboard

# copy custom flow
WORKDIR /data
COPY ./flows.json flows.json

# expose port to host
EXPOSE 1880
